### PR TITLE
Adds a basic Dockerfile to build the application with.

### PR DESCRIPTION
**Pull request by msolberg**
Adds support for specifying your Mongo URL via environment variable.
Gives the package a more specific name and version.

### CODE REVIEW

**Comment by jeremiahbuckley** [comment]
this is awesome.

**Comment by msolberg** [comment]
Now I just need to add a k8s pod definition which has a mongo sidecar and
we're in business.

**Comment by jeremiahbuckley** [comment]
Just learned that kubernetes is also called k8s. 
On their website they say "K8s is an abbreviation derived by replacing the 8 letters “ubernete” with 8." which answers the question without answering it.

I was planning on building the UI out as a separate repo. Working on that in the evenings now. The main reason for this is: I don't know a lot of these libraries and frameworks and it would be easier for me to separate out the "angular / ui" framework stuff from the "mongo / orm" framework stuff and understand them separately.

**Comment by jeremiahbuckley** [comment]
oh, ah... read their explanation too quickly and missed the important detail '8 letters'. I thought that ubernete meant 8 in some weird way.

**Pull request merged**
