### PR TITLE
API Fixes

### PR DESCRIPTION
**Pull request by msolberg**
This adds some discover-ability to the API.
It only adds relative URIs. A better approach which would allow for full URIs would be something like https://github.com/john-doherty/express-hateoas-links.

### CODE REVIEW

**Comment by jeremiahbuckley** [comment]
very cool, I thought I was kind of hateos compliant, but these virtual links. so hateful! 2 tests broke, but I think that reflects on the fact that it's largely impossible to run the tests. fix pull request coming.

**Comment by msolberg** [comment]
That's odd - were they the frisby tests or the mocha tests? I ran both
suites before I committed.

Michael.

**Comment by jeremiahbuckley** [comment]
frisby tests...GET candidates with votes blew up because the return json is different (and the delete after blew up because I am faking out the links in the test, need the hateos).

**Comment by msolberg** [comment]
I see it now. I'll fix that, since I broke it.

Michael.

**Pull request merged**
